/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminQuizzesRouteImport } from './routes/admin.quizzes'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminGcoinsRouteImport } from './routes/admin.gcoins'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'
import { Route as AppQuizzesRouteImport } from './routes/_app.quizzes'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLessonsRouteImport } from './routes/_app.lessons'
import { Route as AppGamesRouteImport } from './routes/_app.games'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppActivitiesRouteImport } from './routes/_app.activities'
import { Route as AppQuizzesIdRouteImport } from './routes/_app.quizzes_.$id'
import { Route as AppGroupGroupIdRouteImport } from './routes/_app.group.$groupId'
import { Route as AppDmPeerIdRouteImport } from './routes/_app.dm.$peerId'
import { Route as AppActivitiesIdRouteImport } from './routes/_app.activities_.$id'
import { Route as AppLessonsReviewersIdRouteImport } from './routes/_app.lessons_.reviewers.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizzesRoute = AdminQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGcoinsRoute = AdminGcoinsRouteImport.update({
  id: '/gcoins',
  path: '/gcoins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsRoute = AppLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIdRoute = AppQuizzesIdRouteImport.update({
  id: '/quizzes_/$id',
  path: '/quizzes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupGroupIdRoute = AppGroupGroupIdRouteImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppDmPeerIdRoute = AppDmPeerIdRouteImport.update({
  id: '/dm/$peerId',
  path: '/dm/$peerId',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesIdRoute = AppActivitiesIdRouteImport.update({
  id: '/activities_/$id',
  path: '/activities/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsReviewersIdRoute = AppLessonsReviewersIdRouteImport.update({
  id: '/lessons_/reviewers/$id',
  path: '/lessons/reviewers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/activities': typeof AppActivitiesRoute
  '/attendance': typeof AppAttendanceRoute
  '/chat': typeof AppChatRoute
  '/feedback': typeof AppFeedbackRoute
  '/games': typeof AppGamesRoute
  '/lessons': typeof AppLessonsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/quizzes': typeof AppQuizzesRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/gcoins': typeof AdminGcoinsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/': typeof AdminIndexRoute
  '/activities/$id': typeof AppActivitiesIdRoute
  '/dm/$peerId': typeof AppDmPeerIdRoute
  '/group/$groupId': typeof AppGroupGroupIdRoute
  '/quizzes/$id': typeof AppQuizzesIdRoute
  '/lessons/reviewers/$id': typeof AppLessonsReviewersIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/activities': typeof AppActivitiesRoute
  '/attendance': typeof AppAttendanceRoute
  '/chat': typeof AppChatRoute
  '/feedback': typeof AppFeedbackRoute
  '/games': typeof AppGamesRoute
  '/lessons': typeof AppLessonsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/quizzes': typeof AppQuizzesRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/gcoins': typeof AdminGcoinsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/activities/$id': typeof AppActivitiesIdRoute
  '/dm/$peerId': typeof AppDmPeerIdRoute
  '/group/$groupId': typeof AppGroupGroupIdRoute
  '/quizzes/$id': typeof AppQuizzesIdRoute
  '/lessons/reviewers/$id': typeof AppLessonsReviewersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/games': typeof AppGamesRoute
  '/_app/lessons': typeof AppLessonsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/quizzes': typeof AppQuizzesRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/gcoins': typeof AdminGcoinsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/activities_/$id': typeof AppActivitiesIdRoute
  '/_app/dm/$peerId': typeof AppDmPeerIdRoute
  '/_app/group/$groupId': typeof AppGroupGroupIdRoute
  '/_app/quizzes_/$id': typeof AppQuizzesIdRoute
  '/_app/lessons_/reviewers/$id': typeof AppLessonsReviewersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/activities'
    | '/attendance'
    | '/chat'
    | '/feedback'
    | '/games'
    | '/lessons'
    | '/notifications'
    | '/profile'
    | '/quizzes'
    | '/admin/activities'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/feedback'
    | '/admin/games'
    | '/admin/gcoins'
    | '/admin/lessons'
    | '/admin/quizzes'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/'
    | '/activities/$id'
    | '/dm/$peerId'
    | '/group/$groupId'
    | '/quizzes/$id'
    | '/lessons/reviewers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/activities'
    | '/attendance'
    | '/chat'
    | '/feedback'
    | '/games'
    | '/lessons'
    | '/notifications'
    | '/profile'
    | '/quizzes'
    | '/admin/activities'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/feedback'
    | '/admin/games'
    | '/admin/gcoins'
    | '/admin/lessons'
    | '/admin/quizzes'
    | '/admin/students'
    | '/admin/subjects'
    | '/'
    | '/admin'
    | '/activities/$id'
    | '/dm/$peerId'
    | '/group/$groupId'
    | '/quizzes/$id'
    | '/lessons/reviewers/$id'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/_app/activities'
    | '/_app/attendance'
    | '/_app/chat'
    | '/_app/feedback'
    | '/_app/games'
    | '/_app/lessons'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/quizzes'
    | '/admin/activities'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/feedback'
    | '/admin/games'
    | '/admin/gcoins'
    | '/admin/lessons'
    | '/admin/quizzes'
    | '/admin/students'
    | '/admin/subjects'
    | '/_app/'
    | '/admin/'
    | '/_app/activities_/$id'
    | '/_app/dm/$peerId'
    | '/_app/group/$groupId'
    | '/_app/quizzes_/$id'
    | '/_app/lessons_/reviewers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quizzes': {
      id: '/admin/quizzes'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminQuizzesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gcoins': {
      id: '/admin/gcoins'
      path: '/gcoins'
      fullPath: '/admin/gcoins'
      preLoaderRoute: typeof AdminGcoinsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/quizzes': {
      id: '/_app/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons': {
      id: '/_app/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AppLessonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games': {
      id: '/_app/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes_/$id': {
      id: '/_app/quizzes_/$id'
      path: '/quizzes/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof AppQuizzesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/group/$groupId': {
      id: '/_app/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof AppGroupGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dm/$peerId': {
      id: '/_app/dm/$peerId'
      path: '/dm/$peerId'
      fullPath: '/dm/$peerId'
      preLoaderRoute: typeof AppDmPeerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities_/$id': {
      id: '/_app/activities_/$id'
      path: '/activities/$id'
      fullPath: '/activities/$id'
      preLoaderRoute: typeof AppActivitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons_/reviewers/$id': {
      id: '/_app/lessons_/reviewers/$id'
      path: '/lessons/reviewers/$id'
      fullPath: '/lessons/reviewers/$id'
      preLoaderRoute: typeof AppLessonsReviewersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppChatRoute: typeof AppChatRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppGamesRoute: typeof AppGamesRoute
  AppLessonsRoute: typeof AppLessonsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuizzesRoute: typeof AppQuizzesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppActivitiesIdRoute: typeof AppActivitiesIdRoute
  AppDmPeerIdRoute: typeof AppDmPeerIdRoute
  AppGroupGroupIdRoute: typeof AppGroupGroupIdRoute
  AppQuizzesIdRoute: typeof AppQuizzesIdRoute
  AppLessonsReviewersIdRoute: typeof AppLessonsReviewersIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppChatRoute: AppChatRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppGamesRoute: AppGamesRoute,
  AppLessonsRoute: AppLessonsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuizzesRoute: AppQuizzesRoute,
  AppIndexRoute: AppIndexRoute,
  AppActivitiesIdRoute: AppActivitiesIdRoute,
  AppDmPeerIdRoute: AppDmPeerIdRoute,
  AppGroupGroupIdRoute: AppGroupGroupIdRoute,
  AppQuizzesIdRoute: AppQuizzesIdRoute,
  AppLessonsReviewersIdRoute: AppLessonsReviewersIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminGcoinsRoute: typeof AdminGcoinsRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminQuizzesRoute: typeof AdminQuizzesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminGcoinsRoute: AdminGcoinsRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminQuizzesRoute: AdminQuizzesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
