/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminQuizzesRouteImport } from './routes/admin.quizzes'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'
import { Route as AppQuizzesRouteImport } from './routes/_app.quizzes'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppLessonsRouteImport } from './routes/_app.lessons'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppActivitiesRouteImport } from './routes/_app.activities'
import { Route as AppQuizzesIdRouteImport } from './routes/_app.quizzes.$id'
import { Route as AppDmPeerIdRouteImport } from './routes/_app.dm.$peerId'
import { Route as AppActivitiesIdRouteImport } from './routes/_app.activities.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizzesRoute = AdminQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsRoute = AppLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIdRoute = AppQuizzesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppQuizzesRoute,
} as any)
const AppDmPeerIdRoute = AppDmPeerIdRouteImport.update({
  id: '/dm/$peerId',
  path: '/dm/$peerId',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesIdRoute = AppActivitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppActivitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/activities': typeof AppActivitiesRouteWithChildren
  '/attendance': typeof AppAttendanceRoute
  '/chat': typeof AppChatRoute
  '/lessons': typeof AppLessonsRoute
  '/profile': typeof AppProfileRoute
  '/quizzes': typeof AppQuizzesRouteWithChildren
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/activities/$id': typeof AppActivitiesIdRoute
  '/dm/$peerId': typeof AppDmPeerIdRoute
  '/quizzes/$id': typeof AppQuizzesIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/activities': typeof AppActivitiesRouteWithChildren
  '/attendance': typeof AppAttendanceRoute
  '/chat': typeof AppChatRoute
  '/lessons': typeof AppLessonsRoute
  '/profile': typeof AppProfileRoute
  '/quizzes': typeof AppQuizzesRouteWithChildren
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/activities/$id': typeof AppActivitiesIdRoute
  '/dm/$peerId': typeof AppDmPeerIdRoute
  '/quizzes/$id': typeof AppQuizzesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/activities': typeof AppActivitiesRouteWithChildren
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/lessons': typeof AppLessonsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/quizzes': typeof AppQuizzesRouteWithChildren
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/activities/$id': typeof AppActivitiesIdRoute
  '/_app/dm/$peerId': typeof AppDmPeerIdRoute
  '/_app/quizzes/$id': typeof AppQuizzesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/activities'
    | '/attendance'
    | '/chat'
    | '/lessons'
    | '/profile'
    | '/quizzes'
    | '/admin/activities'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/lessons'
    | '/admin/quizzes'
    | '/admin/students'
    | '/admin/'
    | '/activities/$id'
    | '/dm/$peerId'
    | '/quizzes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/activities'
    | '/attendance'
    | '/chat'
    | '/lessons'
    | '/profile'
    | '/quizzes'
    | '/admin/activities'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/lessons'
    | '/admin/quizzes'
    | '/admin/students'
    | '/'
    | '/admin'
    | '/activities/$id'
    | '/dm/$peerId'
    | '/quizzes/$id'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/_app/activities'
    | '/_app/attendance'
    | '/_app/chat'
    | '/_app/lessons'
    | '/_app/profile'
    | '/_app/quizzes'
    | '/admin/activities'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/banners'
    | '/admin/lessons'
    | '/admin/quizzes'
    | '/admin/students'
    | '/_app/'
    | '/admin/'
    | '/_app/activities/$id'
    | '/_app/dm/$peerId'
    | '/_app/quizzes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quizzes': {
      id: '/admin/quizzes'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminQuizzesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/quizzes': {
      id: '/_app/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons': {
      id: '/_app/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AppLessonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes/$id': {
      id: '/_app/quizzes/$id'
      path: '/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof AppQuizzesIdRouteImport
      parentRoute: typeof AppQuizzesRoute
    }
    '/_app/dm/$peerId': {
      id: '/_app/dm/$peerId'
      path: '/dm/$peerId'
      fullPath: '/dm/$peerId'
      preLoaderRoute: typeof AppDmPeerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities/$id': {
      id: '/_app/activities/$id'
      path: '/$id'
      fullPath: '/activities/$id'
      preLoaderRoute: typeof AppActivitiesIdRouteImport
      parentRoute: typeof AppActivitiesRoute
    }
  }
}

interface AppActivitiesRouteChildren {
  AppActivitiesIdRoute: typeof AppActivitiesIdRoute
}

const AppActivitiesRouteChildren: AppActivitiesRouteChildren = {
  AppActivitiesIdRoute: AppActivitiesIdRoute,
}

const AppActivitiesRouteWithChildren = AppActivitiesRoute._addFileChildren(
  AppActivitiesRouteChildren,
)

interface AppQuizzesRouteChildren {
  AppQuizzesIdRoute: typeof AppQuizzesIdRoute
}

const AppQuizzesRouteChildren: AppQuizzesRouteChildren = {
  AppQuizzesIdRoute: AppQuizzesIdRoute,
}

const AppQuizzesRouteWithChildren = AppQuizzesRoute._addFileChildren(
  AppQuizzesRouteChildren,
)

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRouteWithChildren
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppChatRoute: typeof AppChatRoute
  AppLessonsRoute: typeof AppLessonsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuizzesRoute: typeof AppQuizzesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppDmPeerIdRoute: typeof AppDmPeerIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRouteWithChildren,
  AppAttendanceRoute: AppAttendanceRoute,
  AppChatRoute: AppChatRoute,
  AppLessonsRoute: AppLessonsRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuizzesRoute: AppQuizzesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppDmPeerIdRoute: AppDmPeerIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminQuizzesRoute: typeof AdminQuizzesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminQuizzesRoute: AdminQuizzesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
